# Generated by Django 4.2.5 on 2023-10-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_test_hangman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangman',
            old_name='subtitle',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='hangman',
            name='title',
        ),
        migrations.AddField(
            model_name='hangman',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
