# Generated by Django 5.1.5 on 2025-07-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_subtitle_hangman_answer_remove_hangman_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hangman',
        ),
    ]
